name: Display GH_TOKEN
on: 
  workflow_dispatch:  # Manual trigger option

jobs:
  show-token:
    runs-on: ubuntu-latest
    environment: envis  # Specify your environment name here
    steps:
      - name: Display GH_TOKEN
        run: |
          echo "GH_TOKEN: $GH_TOKEN"
