name: Display GH_TOKEN
on: 
  workflow_dispatch:  # Manual trigger option

jobs:
  show-token:
    runs-on: ubuntu-latest
    environment: envis  # Specify your environment name here
    steps:
      - name: Check if GH_TOKEN is set
        run: |
          if [ -z "$GH_TOKEN" ]; then
            echo "GH_TOKEN is not set"
          else
            echo "GH_TOKEN is set"
          fi
