name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch: # Manual trigger option
jobs:
  update-gist:
    runs-on: ubuntu-latest
    environment: env # Specify your environment name here
    steps:
      - uses: actions/checkout@master
      - name: Check environment variables
        run: |
          echo "GH_TOKEN: $GH_TOKEN"
          echo "GIST_ID: $GIST_ID"
          echo "WAKATIME_API_KEY: $WAKATIME_API_KEY"
      - name: Update gist
        uses: dmisl/waka-box@master
        env:
          GH_TOKEN: ${{ env.GH_TOKEN }} # Accessing the environment variable
          GIST_ID: ${{ env.GIST_ID }}
          WAKATIME_API_KEY: ${{ env.WAKATIME_API_KEY }}
