name: Test Environment Variables
on: [push]
jobs:
  test-env-vars:
    runs-on: ubuntu-latest
    environment: envis  # Make sure this matches your environment name
    steps:
      - name: Check environment variables
        run: |
          echo ${{ env.GH_TOKEN }}
